//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCamilla
    {
        public int idASignacion { get; set; }
        public int numeroCamilla { get; set; }
        public int idpaciente { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
    
        public virtual Camilla Camilla { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
