//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HospitalEntities : DbContext
    {
        public HospitalEntities()
            : base("name=HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsignacionCamilla> AsignacionCamilla { get; set; }
        public virtual DbSet<Camilla> Camilla { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int PA_ActIntento(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ActIntento", usuarioParameter);
        }
    
        public virtual ObjectResult<PA_ConsultarAutenticacion_Result> PA_ConsultarAutenticacion(string nomus, string passw)
        {
            var nomusParameter = nomus != null ?
                new ObjectParameter("nomus", nomus) :
                new ObjectParameter("nomus", typeof(string));
    
            var passwParameter = passw != null ?
                new ObjectParameter("passw", passw) :
                new ObjectParameter("passw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_ConsultarAutenticacion_Result>("PA_ConsultarAutenticacion", nomusParameter, passwParameter);
        }
    
        public virtual ObjectResult<PA_ConsultarPerfilesUsuario_Result> PA_ConsultarPerfilesUsuario(string nomusuario)
        {
            var nomusuarioParameter = nomusuario != null ?
                new ObjectParameter("nomusuario", nomusuario) :
                new ObjectParameter("nomusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_ConsultarPerfilesUsuario_Result>("PA_ConsultarPerfilesUsuario", nomusuarioParameter);
        }
    
        public virtual int Pa_ResetIntento(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_ResetIntento", usuarioParameter);
        }
    
        public virtual int PA_ResetIntentoAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_ResetIntentoAll");
        }
    
        public virtual ObjectResult<Nullable<int>> Pa_VerificarIntento(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pa_VerificarIntento", usuarioParameter);
        }
    }
}
